import pytest
from playwright.sync_api import sync_playwright
from selenium.webdriver.common.devtools.v121 import page
from utils.config import BASE_URL
from utils.config import USERNAME
from utils.config import PASSWORD
from pages.login_page import LoginPage
from utils.logger import setup_logger
import time

logger = setup_logger()


@pytest.fixture(scope="class")
def test_setup(request):
    logger.info("Setting up the test environment")
    playwright = sync_playwright().start()
    browser = playwright.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://mypaperlessoffice.com/app/login.aspx")
    request.cls.page = page
    request.cls.browser = browser
    yield
    logger.info("Tearing down the test environment")
    browser.close()
    playwright.stop()


@pytest.mark.usefixtures("test_setup")
class TestLogin:
    def test_valid_login(self):
        logger.info("Starting test: test_valid_login")
        login_page = LoginPage(self.page)
        login_page.enter_username(USERNAME)
        login_page.enter_password(PASSWORD)
        login_page.click_login()


        login_page.clik_ee_role()
        login_page.enter_employer("Employer")
        login_page.press_enter()
        login_page.click_go_button()

        # login_page.verify_title()

        # Add assertions to verify successful login
        logger.info("Completed test: test_valid_login")

        time.sleep(10)

    def test_ee_smoke(self):

        logger.info("Starting test: test_Page_Crashes")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Employees/NewHireReport.aspx")
        self.page.goto(BASE_URL+ "/Sys/EmployerManager/Employees/EditEmployees.aspx")
        self.page.goto(BASE_URL+ "/Sys/EmployerManager/Employees/TerminateEmployee.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Employees/TerminationReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/UserManagement/ManagerAssignment.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/CompanyManagement/CompanyLevelsHierarchy.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Employees/JobTitles.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/WelcomeEmail/WelcomeEmailReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Onboarding/OnboardingReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Onboarding/OnboardingTemplateSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Onboarding/OnboardingDashboardSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Onboarding/OnboardingReminderAlertSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Orientation/EmployeeOrientationReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Announcements/Announcements.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewSetupWizard.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewDashboard.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewJournal.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewChecklists.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewSessions.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewCriteriaLibrary.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewCommentTemplates.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewWorkflows.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewReports.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewFeedback.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewReminderAlertSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewGoalReminderAlertSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/FAQ/KnowledgeBase.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Kudos/KudosSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Kudos/ManageKudos.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Kudos/KudosReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/PerformanceReviewGoals.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Employees/Succession.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeWarnings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/CompanyHolidays.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/HR/EmployeeSuggestionReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/EnrollmentWizard/BenefitEnrollmentWizard.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Setup/BenefitPlans.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/LifeEvents/LifeEventsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/BenefitEdiReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Templates/BenefitDurationTemplates.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Templates/BenefitCoverages.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Templates/BenefitComparisonSummaryTemplates.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Templates/FlexCredits.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Templates/BenefitForms.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Benefits/Reports/BeneficiariesReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Benefits/Reports/DependentsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/BenefitEnrollmentReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Setup/BenefitCloneReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/BenefitEdiReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/BenefitsActivitiesReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/EnrollmentsSummaryReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/InsuranceApplicationsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/Benefit401KPlanEnrollmentReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Benefits/Reports/BenefitsConsolidatedBillingReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/TimeoffManagement/TimeoffRequest.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/TimeoffManagement/TimeoffApprovalDenialReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/TimeoffManagement/TimeoffBalanceReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/TimeoffManagement/TimeoffCalendar.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/TimeoffManagement/TimeoffMiscellaneousSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/TimeOffAccruals/TimeOffAccrualsProfiles.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Payroll/CalendarRules.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Payroll/HolidayRules.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Payroll/TimeSheetSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Payroll/ImportTimePunches.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Payroll/TimeCardType.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Payroll/PayrollBatches.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/CustomReport/CustomReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Reports/DeductionApprovalReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/TaskManagement/ScheduledReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/AnniversaryReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/BirthdayReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EducationReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmergencyContactReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeNotesReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EquipmentReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/LicenseTrackingReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeCountReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeTurnoverReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeUserAccountsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeEEOReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/I9/Ei9ExpirationReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/EmployeeSkillReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Employees/OrganizationChart.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Reports/WorkForceAge.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Reports/Vet4212.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Reports/PayHistory.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/Reports/PayRates.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/HR/TerminationTrend.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Reports/SyncChangeReport.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/FileCabinet/FileCabinet.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Files/EmployeeForms/EmployeeForms.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/Files/EmployeeForms/EmployeeFormsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ScheduleManagement/EmployeeSchedule.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ScheduleManagement/ScheduleDisplaySettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ScheduleManagement/EmployeeRejectedShift.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/JobPostsSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/ApplicationFormSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/ManageInterviewsChecklists.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/ApplicantTrackingSystem/JobPostingStageSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/ApplicantsRecruitmentPipeline.aspx")
        self.page.goto(BASE_URL + "/Sys/Employer/ApplicantTrackingSystem/ExternalJobBoardSettings.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/ApplicantsReport.aspx")
        self.page.goto(BASE_URL + "/Sys/EmployerManager/ApplicantTrackingSystem/Quizzes.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Tasks/Kanban.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Tasks/Task.aspx'")
        self.page.goto(BASE_URL + "/Sys/Common/Tasks/TaskGroup.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/Tasks/TaskList.aspx")
        self.page.goto(BASE_URL + "/Sys/Common/MessageCenter/Messages.aspx")
        self.page.goto(BASE_URL + "/Sys/UserProfile.aspx")

        